name: GCP App Engine Deploy
run-name: ${{ github.actor }} is deploying ${{ github.repository }} to App Engine
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'auth'
      name: 'Gcp auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - id: 'deploy'
      name: Google AppEngine deploy
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        env_vars: |-
          SECRET=${{ secrets.SECRET }}
          DB_URI=${{ secrets.DB_URI }}
    - id: 'test'
